language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test Tests/Tests.csproj
  - dotnet run --project TravisSampleWeb/TravisSampleWeb.csproj
